fn main() {
    println!("cargo:rerun-if-changed=config.example.toml");
    println!("cargo:rerun-if-changed=rustnfssvc.exe.manifest");

    // ── Windows Manifest embedding ──────────────────────────────────────────
    // Embed rustnfssvc.exe.manifest into the binary so that:
    //   1. `longPathAware = true` is declared — Win32 accepts paths > 260 chars
    //      when HKLM\…\FileSystem\LongPathsEnabled = 1 is also set.
    //   2. UAC requestedExecutionLevel is set to asInvoker (no unwanted elevation).
    //
    // For MSVC toolchain: link.exe is invoked with /MANIFEST:EMBED + /MANIFESTINPUT.
    // For GNU (MinGW) toolchain: windres compiles the manifest into a .res object.
    // Only activated when the target triple contains "windows".
    // ─────────────────────────────────────────────────────────────────────────
    let target = std::env::var("TARGET").unwrap_or_default();
    if target.contains("windows") {
        embed_manifest(&target);
    }
}

fn embed_manifest(target: &str) {
    use std::env;
    use std::path::PathBuf;

    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is always set by Cargo");
    let manifest_path = PathBuf::from(&manifest_dir).join("rustnfssvc.exe.manifest");

    if !manifest_path.exists() {
        println!(
            "cargo:warning=rustnfssvc.exe.manifest not found at {}; \
             long-path support via manifest will not be embedded.",
            manifest_path.display()
        );
        return;
    }

    let is_msvc = target.contains("msvc");

    if is_msvc {
        // MSVC link.exe: embed the manifest directly into the PE binary.
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!(
            "cargo:rustc-link-arg=/MANIFESTINPUT:{}",
            manifest_path.display()
        );
    } else {
        // GNU (MinGW) toolchain: compile the manifest via windres → .res → link.
        let out_dir = env::var("OUT_DIR").expect("OUT_DIR is always set by Cargo");
        let rc_path = PathBuf::from(&out_dir).join("manifest.rc");
        let res_path = PathBuf::from(&out_dir).join("manifest.res");

        // RT_MANIFEST resource type = 24; resource ID = 1 for executables.
        let rc_content = format!(
            "// Auto-generated by build.rs\n\
             1 24 \"{}\"\n",
            manifest_path.display().to_string().replace('\\', "/")
        );
        std::fs::write(&rc_path, rc_content).expect("Failed to write manifest.rc");

        // Determine the windres binary name.
        let windres = env::var("WINDRES").unwrap_or_else(|_| {
            if target.contains("x86_64") {
                "x86_64-w64-mingw32-windres".to_string()
            } else if target.contains("i686") {
                "i686-w64-mingw32-windres".to_string()
            } else {
                "windres".to_string()
            }
        });

        let status = std::process::Command::new(&windres)
            .args([
                rc_path.to_str().unwrap(),
                "-O", "coff",
                "-o", res_path.to_str().unwrap(),
            ])
            .status();

        match status {
            Ok(s) if s.success() => {
                println!("cargo:rustc-link-arg={}", res_path.display());
            }
            Ok(s) => {
                println!(
                    "cargo:warning=windres exited with status {} — manifest not embedded. \
                     Switch to the MSVC toolchain for reliable manifest embedding.",
                    s
                );
            }
            Err(e) => {
                println!(
                    "cargo:warning=Could not run '{}': {} — manifest not embedded. \
                     Install MinGW windres or switch to the MSVC toolchain.",
                    windres, e
                );
            }
        }
    }
}
